// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKWvRDCl1CcY1_wV0iE_UMeXHsO1J6gUA',
    appId: '1:516765806:web:3944ce646951438f200e7f',
    messagingSenderId: '516765806',
    projectId: 'expense-tracker-9d58e',
    authDomain: 'expense-tracker-9d58e.firebaseapp.com',
    storageBucket: 'expense-tracker-9d58e.firebasestorage.app',
    measurementId: 'G-4D5YXDERJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MGqVYJRBeKOpuaThLR2jqmNwxhQXqOE',
    appId: '1:516765806:android:123d006a02ba34f3200e7f',
    messagingSenderId: '516765806',
    projectId: 'expense-tracker-9d58e',
    storageBucket: 'expense-tracker-9d58e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2NI7ftMMEAUEz9VF61yzo_depUrxAv5k',
    appId: '1:516765806:ios:f98900b964dcd6b9200e7f',
    messagingSenderId: '516765806',
    projectId: 'expense-tracker-9d58e',
    storageBucket: 'expense-tracker-9d58e.firebasestorage.app',
    iosBundleId: 'com.example.tweeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2NI7ftMMEAUEz9VF61yzo_depUrxAv5k',
    appId: '1:516765806:ios:ccc282a16965d37f200e7f',
    messagingSenderId: '516765806',
    projectId: 'expense-tracker-9d58e',
    storageBucket: 'expense-tracker-9d58e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKWvRDCl1CcY1_wV0iE_UMeXHsO1J6gUA',
    appId: '1:516765806:web:3c050ddc768be1fb200e7f',
    messagingSenderId: '516765806',
    projectId: 'expense-tracker-9d58e',
    authDomain: 'expense-tracker-9d58e.firebaseapp.com',
    storageBucket: 'expense-tracker-9d58e.firebasestorage.app',
    measurementId: 'G-EMLJG013TG',
  );
}
